apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/app-deployment.yaml
  - base/app-service.yaml
  - base/nginx-configmap.yaml
  - base/nginx-deployment.yaml
  - base/nginx-service.yaml
  - base/haproxy-configmap.yaml
  - base/haproxy-deployment.yaml
  - base/haproxy-service.yaml
